@php
$preset = App\IntegrationProvider::tryFrom((string) request('provider')) ?? $integration?->provider ?? App\IntegrationProvider::GenericRest;
$modelSuggestions = $preset->suggestedModels();
@endphp
<div class="grid gap-5 lg:grid-cols-2">
<label><span class="mb-1 block text-sm font-semibold">Ajans</span><select name="agency_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5">@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected((string)old('agency_id',$integration?->agency_id)===(string)$agency->id)>{{ $agency->name }}</option>@endforeach</select></label>
<label><span class="mb-1 block text-sm font-semibold">Entegrasyon adı</span><input name="name" value="{{ old('name',$integration?->name ?? $preset->label()) }}" maxlength="150" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"></label>
<label><span class="mb-1 block text-sm font-semibold">Sağlayıcı</span><select id="provider" name="provider" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5">@foreach($providers as $provider)<option value="{{ $provider->value }}" data-url="{{ $provider->defaultBaseUrl() }}" data-ai="{{ $provider->isAi() ? 1 : 0 }}" data-models="{{ implode('|',$provider->suggestedModels()) }}" @selected(old('provider',$preset->value)===$provider->value)>{{ $provider->label() }}</option>@endforeach</select></label>
<label id="model-field"><span class="mb-1 block text-sm font-semibold">Yapay zekâ modeli</span><input id="model" name="model" value="{{ old('model',$integration?->model ?? ($modelSuggestions[0] ?? '')) }}" list="model-list" maxlength="150" placeholder="Örn. gpt-5" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"><datalist id="model-list">@foreach($modelSuggestions as $model)<option value="{{ $model }}"></option>@endforeach</datalist></label>
<label class="lg:col-span-2"><span class="mb-1 block text-sm font-semibold">API adresi</span><input id="base_url" type="url" name="base_url" value="{{ old('base_url',$integration?->base_url ?? $preset->defaultBaseUrl()) }}" required maxlength="1000" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"><small class="mt-1 block text-slate-500">Sağlayıcı seçildiğinde güvenli varsayılan test adresi otomatik gelir.</small></label>
<label><span class="mb-1 block text-sm font-semibold">Kimlik doğrulama</span><select name="auth_type" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5">@foreach($authTypes as $authType)<option value="{{ $authType->value }}" @selected(old('auth_type',$integration?->auth_type?->value ?? $preset->defaultAuthType()->value)===$authType->value)>{{ $authType->label() }}</option>@endforeach</select></label>
<label><span class="mb-1 block text-sm font-semibold">API anahtarı başlığı</span><input name="api_key_header" value="{{ old('api_key_header',$integration?->api_key_header ?? $preset->defaultApiKeyHeader()) }}" maxlength="100" placeholder="X-API-Key" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"></label>
<label><span class="mb-1 block text-sm font-semibold">Kullanıcı adı <small class="text-slate-500">(yalnız Basic)</small></span><input name="username" value="{{ old('username',$integration?->username) }}" maxlength="255" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"></label>
<label><span class="mb-1 block text-sm font-semibold">API anahtarı / token / parola</span><input type="password" name="credential" maxlength="4000" @required(!$integration) autocomplete="new-password" placeholder="{{ $integration ? 'Değişmeyecekse boş bırakın' : 'API anahtarını yapıştırın' }}" class="w-full rounded-xl border border-cyan-400/30 bg-slate-900 px-3 py-2.5"><small class="mt-1 block text-emerald-300/80">Şifreli saklanır ve tekrar gösterilmez.</small></label>
<label><span class="mb-1 block text-sm font-semibold">Öncelik</span><input type="number" name="priority" value="{{ old('priority',$integration?->priority ?? 50) }}" min="1" max="100" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"><small class="text-slate-500">Küçük sayı önce denenir.</small></label>
<label><span class="mb-1 block text-sm font-semibold">Zaman aşımı</span><input type="number" name="timeout_seconds" value="{{ old('timeout_seconds',$integration?->timeout_seconds ?? 15) }}" min="2" max="60" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"></label>
<div class="flex flex-wrap items-end gap-3 lg:col-span-2"><input type="hidden" name="is_active" value="0"><label class="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5"><input type="checkbox" name="is_active" value="1" @checked((bool)old('is_active',$integration?->is_active ?? true))> Etkin</label><input type="hidden" name="is_default" value="0"><label class="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5"><input type="checkbox" name="is_default" value="1" @checked((bool)old('is_default',$integration?->is_default ?? false))> Bu ajansın varsayılan yapay zekâsı</label></div>
</div>
<script>
document.getElementById('provider')?.addEventListener('change', function () {
 const option=this.options[this.selectedIndex], url=document.getElementById('base_url'), model=document.getElementById('model');
 if (option.dataset.url) url.value=option.dataset.url;
 const models=(option.dataset.models||'').split('|').filter(Boolean);
 if (models.length) model.value=models[0];
});
</script>
