<div class="grid gap-5 sm:grid-cols-2">
    <div class="sm:col-span-2"><label for="name" class="mb-2 block text-sm font-semibold">Ad soyad</label><input id="name" name="name" value="{{ old('name', $user?->name) }}" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div class="sm:col-span-2"><label for="email" class="mb-2 block text-sm font-semibold">E-posta</label><input id="email" name="email" type="email" value="{{ old('email', $user?->email) }}" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div class="sm:col-span-2"><label for="password" class="mb-2 block text-sm font-semibold">Parola {{ $user ? '(değişmeyecekse boş bırakın)' : '' }}</label><input id="password" name="password" type="password" @required(! $user) autocomplete="new-password" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"><p class="mt-2 text-xs text-slate-500">İstediğiniz uzunluk ve biçimde parola girebilirsiniz.</p></div>
    <div><label for="role" class="mb-2 block text-sm font-semibold">Rol</label><select id="role" name="role" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300">@foreach ($roles as $role)<option value="{{ $role->value }}" @selected(old('role', $user?->role?->value ?? App\UserRole::Editor->value) === $role->value)>{{ $role->label() }}</option>@endforeach</select></div>
    @if (auth()->user()->isSystemAdministrator())
        <div><label for="agency_id" class="mb-2 block text-sm font-semibold">Ajans</label><select id="agency_id" name="agency_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"><option value="">Ajans yok (yalnızca sistem yöneticisi)</option>@foreach ($agencies as $agency)<option value="{{ $agency->id }}" @selected((string) old('agency_id', $user?->agency_id) === (string) $agency->id)>{{ $agency->name }}</option>@endforeach</select></div>
    @else
        <input type="hidden" name="agency_id" value="{{ auth()->user()->agency_id }}">
    @endif
    @if (! $user)<div class="flex items-end"><input type="hidden" name="is_active" value="0"><label class="flex w-full items-center gap-3 rounded-xl border border-white/10 px-4 py-3"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', true))> Kullanıcı aktif</label></div>@endif
</div>
<div class="mt-8 flex gap-3"><button class="rounded-xl bg-cyan-300 px-5 py-3 font-bold text-slate-950 hover:bg-cyan-200">{{ $submitLabel }}</button><a href="{{ route('users.index') }}" class="rounded-xl border border-white/10 px-5 py-3 hover:bg-white/5">Vazgeç</a></div>