<x-layouts.app title="Kullanıcılar">
    <section>
        <div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-sm font-bold tracking-[.18em] text-cyan-300">KULLANICI YÖNETİMİ</p><h1 class="mt-3 text-4xl font-black">Kullanıcılar</h1><p class="mt-2 text-slate-400">Ekip erişimini, ajanslarını, rollerini ve hesap durumlarını yönetin.</p></div><a href="{{ route('users.create') }}" class="rounded-xl bg-cyan-300 px-5 py-3 text-center font-bold text-slate-950 hover:bg-cyan-200">+ Kullanıcı ekle</a></div>
        <div class="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[.04]"><div class="overflow-x-auto"><table class="w-full text-left"><thead class="border-b border-white/10 bg-white/[.03] text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-4">Kullanıcı</th><th class="px-5 py-4">Ajans</th><th class="px-5 py-4">Rol</th><th class="px-5 py-4">Durum</th><th class="px-5 py-4 text-right">İşlemler</th></tr></thead><tbody class="divide-y divide-white/10">
            @forelse ($users as $user)
                <tr><td class="px-5 py-4"><strong class="block">{{ $user->name }}</strong><span class="text-sm text-slate-400">{{ $user->email }}</span></td><td class="px-5 py-4 text-sm text-slate-300">{{ $user->agency?->name ?? 'Sistem geneli' }}</td><td class="px-5 py-4">{{ $user->role->label() }}</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $user->is_active ? 'bg-emerald-400/10 text-emerald-300' : 'bg-rose-400/10 text-rose-300' }}">{{ $user->is_active ? 'Aktif' : 'Pasif' }}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2">@can('update', $user)<a href="{{ route('users.edit', $user) }}" class="rounded-lg border border-white/10 px-3 py-2 text-sm hover:bg-white/5">Düzenle</a>@endcan @can('updateStatus', $user)<form method="POST" action="{{ route('users.status.update', $user) }}">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $user->is_active ? 0 : 1 }}"><button class="rounded-lg border px-3 py-2 text-sm {{ $user->is_active ? 'border-rose-400/20 text-rose-300' : 'border-emerald-400/20 text-emerald-300' }}" @disabled(auth()->user()->is($user))>{{ $user->is_active ? 'Pasif yap' : 'Aktif et' }}</button></form>@endcan</div></td></tr>
            @empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-400">Henüz kullanıcı yok.</td></tr>@endforelse
        </tbody></table></div>@if ($users->hasPages())<div class="border-t border-white/10 px-5 py-4">{{ $users->links() }}</div>@endif</div>
    </section>
</x-layouts.app>