<x-layouts.app title="SEO Analizi">
    <section class="mx-auto max-w-6xl space-y-7">
        <header class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p class="text-sm font-bold tracking-[.18em] text-cyan-300">DERİN SEO & OTOMATİK SÜZGEÇ</p><h1 class="mt-3 text-4xl font-black">SEO Analizi</h1><p class="mt-2 max-w-3xl text-slate-400">{{ $article->title }}</p></div><a href="{{ route('articles.show', $article) }}" class="rounded-xl border border-white/10 px-5 py-3 text-center hover:bg-white/5">← Habere dön</a></header>
        <form method="POST" action="{{ route('seo.analyze', $article) }}" class="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:flex-row">@csrf<input name="focus_keyword" value="{{ old('focus_keyword', $analysis?->focus_keyword) }}" placeholder="Odak anahtar kelime (boşsa otomatik seçilir)" class="min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"><button class="rounded-xl bg-cyan-300 px-6 py-3 font-bold text-slate-950 hover:bg-cyan-200">{{ $analysis ? 'Yeniden analiz et' : 'SEO analizi başlat' }}</button></form>
        @if ($analysis)
            <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article class="rounded-2xl border border-white/10 bg-white/[.04] p-5"><span class="text-sm text-slate-400">SEO puanı</span><strong class="mt-3 block text-4xl {{ $analysis->score >= 80 ? 'text-emerald-300' : ($analysis->score >= 50 ? 'text-amber-300' : 'text-rose-300') }}">{{ $analysis->score }}<small class="text-base text-slate-500">/100</small></strong></article><article class="rounded-2xl border border-white/10 bg-white/[.04] p-5"><span class="text-sm text-slate-400">Okunabilirlik</span><strong class="mt-3 block text-4xl">{{ $analysis->readability_score }}<small class="text-base text-slate-500">/100</small></strong></article><article class="rounded-2xl border border-white/10 bg-white/[.04] p-5"><span class="text-sm text-slate-400">Kelime sayısı</span><strong class="mt-3 block text-4xl">{{ number_format($analysis->word_count, 0, ',', '.') }}</strong></article><article class="rounded-2xl border border-white/10 bg-white/[.04] p-5"><span class="text-sm text-slate-400">Anahtar yoğunluğu</span><strong class="mt-3 block text-4xl">%{{ number_format($analysis->keyword_density, 2, ',', '.') }}</strong></article></div>
            <div class="grid gap-5 lg:grid-cols-2"><article class="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 class="text-xl font-bold">Arama görünümü</h2><div class="mt-5 rounded-xl bg-white p-5 text-slate-900"><div class="text-sm text-emerald-700">asya.local › haber › {{ $article->slug }}</div><div class="mt-1 text-xl text-blue-700">{{ $analysis->meta_title }}</div><p class="mt-1 text-sm leading-6 text-slate-600">{{ $analysis->meta_description }}</p></div><dl class="mt-5 space-y-3 text-sm"><div><dt class="text-slate-500">Odak kelime</dt><dd class="mt-1 font-bold text-cyan-200">{{ $analysis->focus_keyword }}</dd></div><div><dt class="text-slate-500">Anahtar kelimeler</dt><dd class="mt-2 flex flex-wrap gap-2">@foreach ($analysis->keywords as $keyword)<span class="rounded-full bg-white/5 px-3 py-1">{{ $keyword }}</span>@endforeach</dd></div><div><dt class="text-slate-500">Hashtagler</dt><dd class="mt-2 flex flex-wrap gap-2 text-indigo-300">@foreach ($analysis->hashtags as $hashtag)<span>{{ $hashtag }}</span>@endforeach</dd></div></dl></article>
                <article class="space-y-5"><div class="rounded-2xl border border-rose-400/15 bg-rose-400/[.06] p-6"><h2 class="text-xl font-bold text-rose-200">Tespit edilen sorunlar</h2><ul class="mt-4 space-y-3 text-sm text-slate-300">@forelse ($analysis->issues as $issue)<li class="flex gap-3"><span class="text-rose-300">●</span><span>{{ $issue }}</span></li>@empty<li class="text-emerald-300">SEO sorunu bulunamadı.</li>@endforelse</ul></div><div class="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.06] p-6"><h2 class="text-xl font-bold text-emerald-200">İyileştirme önerileri</h2><ul class="mt-4 space-y-3 text-sm text-slate-300">@forelse ($analysis->recommendations as $recommendation)<li class="flex gap-3"><span class="text-emerald-300">✓</span><span>{{ $recommendation }}</span></li>@empty<li>İçerik mevcut kriterleri karşılıyor.</li>@endforelse</ul></div></article></div>
            <p class="text-right text-xs text-slate-500">Son analiz: {{ $analysis->analyzed_at->format('d.m.Y H:i:s') }}</p>
        @else
            <div class="rounded-2xl border border-dashed border-white/15 p-14 text-center"><strong class="text-xl">Bu haber henüz analiz edilmedi.</strong><p class="mt-2 text-slate-400">Otomatik meta, kelime, hashtag ve kalite puanı üretmek için analizi başlatın.</p></div>
        @endif
    </section>
</x-layouts.app>