<div class="grid gap-5 lg:grid-cols-2">
<label><span class="mb-1 block text-sm font-semibold">Ajans</span><select name="agency_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5">@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected((string)old('agency_id',$mapping?->agency_id)===(string)$agency->id)>{{ $agency->name }}</option>@endforeach</select></label>
<label><span class="mb-1 block text-sm font-semibold">Yayın hedefi</span><select name="publishing_target_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5">@foreach($targets as $target)<option value="{{ $target->id }}" @selected((string)old('publishing_target_id',$mapping?->publishing_target_id)===(string)$target->id)>{{ $target->agency->name }} · {{ $target->name }}</option>@endforeach</select></label>
<label><span class="mb-1 block text-sm font-semibold">Tür</span><select name="type" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5">@foreach($types as $type)<option value="{{ $type->value }}" @selected(old('type',$mapping?->type?->value)===$type->value)>{{ $type->label() }}</option>@endforeach</select></label>
<label><span class="mb-1 block text-sm font-semibold">Yerel terim</span><input name="source_term" value="{{ old('source_term',$mapping?->source_term) }}" maxlength="150" required placeholder="Örn. spor" class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"></label>
<label><span class="mb-1 block text-sm font-semibold">Uzak kimlik</span><input type="number" name="remote_id" value="{{ old('remote_id',$mapping?->remote_id) }}" min="1" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"></label>
<label><span class="mb-1 block text-sm font-semibold">Uzak ad</span><input name="remote_name" value="{{ old('remote_name',$mapping?->remote_name) }}" maxlength="150" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"></label>
<label><span class="mb-1 block text-sm font-semibold">Öncelik</span><input type="number" name="priority" value="{{ old('priority',$mapping?->priority ?? 50) }}" min="0" max="100" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"></label>
<div class="flex items-end"><input type="hidden" name="is_active" value="0"><label class="inline-flex items-center gap-3 rounded-xl border border-white/10 px-4 py-2.5"><input type="checkbox" name="is_active" value="1" @checked((bool)old('is_active',$mapping?->is_active ?? true))><span>Etkin</span></label></div>
</div>
