<x-layouts.app title="Görsel Ekle">
    <section class="mx-auto max-w-5xl space-y-7">
        <header><p class="text-sm font-bold tracking-[.18em] text-fuchsia-300">GÖRSEL MOTORU</p><h1 class="mt-3 text-4xl font-black">Yeni görsel kaynağı</h1><p class="mt-2 text-slate-400">Kaynak görseli denetleyin, arşiv varlığı bağlayın, dosya yükleyin veya özgün AI üretim isteği hazırlayın.</p></header>
        <form method="POST" action="{{ route('visual-assets.store') }}" enctype="multipart/form-data" class="space-y-6 rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:p-7">@csrf
            <div class="grid gap-6 lg:grid-cols-2">
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Görsel adı</span><input name="title" value="{{ old('title') }}" required maxlength="180" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300"></label>
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Ajans</span><select name="agency_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300" @disabled(! auth()->user()->isSystemAdministrator())>@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected((string) old('agency_id', auth()->user()->agency_id) === (string) $agency->id)>{{ $agency->name }}</option>@endforeach</select>@if(! auth()->user()->isSystemAdministrator())<input type="hidden" name="agency_id" value="{{ auth()->user()->agency_id }}">@endif</label>
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Bağlı haber</span><select name="article_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300"><option value="">Medya arşivine ekle</option>@foreach($articles as $article)<option value="{{ $article->id }}" @selected((string) old('article_id', request('article_id')) === (string) $article->id)>{{ $article->title }} · {{ $article->agency->name }}</option>@endforeach</select></label>
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Kaynak türü</span><select name="source_type" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300">@foreach($sourceTypes as $sourceType)<option value="{{ $sourceType->value }}" @selected(old('source_type', App\VisualSourceType::Upload->value) === $sourceType->value)>{{ $sourceType->label() }}</option>@endforeach</select></label>
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Telif durumu</span><select name="copyright_status" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300">@foreach($copyrightStatuses as $copyrightStatus)<option value="{{ $copyrightStatus->value }}" @selected(old('copyright_status', App\CopyrightStatus::Unknown->value) === $copyrightStatus->value)>{{ $copyrightStatus->label() }}</option>@endforeach</select></label>
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Görsel dosyası</span><input type="file" name="image" accept="image/jpeg,image/png,image/webp,image/gif,image/bmp" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-fuchsia-300 file:px-3 file:py-2 file:font-bold file:text-slate-950"><small class="text-slate-500">Manuel yükleme için zorunlu, en fazla 10 MB.</small></label>
                <label class="space-y-2 lg:col-span-2"><span class="text-sm font-bold text-slate-300">Kaynak / arşiv bağlantısı</span><input type="url" name="source_url" value="{{ old('source_url') }}" maxlength="2000" placeholder="https://..." class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300"></label>
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Bildirilen genişlik</span><input type="number" name="width" value="{{ old('width') }}" min="1" max="20000" placeholder="1280" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300"></label>
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Bildirilen yükseklik</span><input type="number" name="height" value="{{ old('height') }}" min="1" max="20000" placeholder="720" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300"></label>
                <label class="space-y-2 lg:col-span-2"><span class="text-sm font-bold text-slate-300">AI üretim promptu</span><textarea name="generation_prompt" rows="5" maxlength="5000" placeholder="Fotogerçekçi, yatay haber kapağı..." class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300">{{ old('generation_prompt') }}</textarea><small class="text-slate-500">AI üretimi seçildiğinde istek entegrasyon sağlayıcısı için kuyruğa hazırlanır.</small></label>
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Alternatif metin</span><input name="alt_text" value="{{ old('alt_text') }}" maxlength="255" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300"></label>
                <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Manşet katmanı</span><input name="headline_overlay" value="{{ old('headline_overlay') }}" maxlength="120" placeholder="Görsele eklenecek kısa manşet" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-fuchsia-300"></label>
            </div>
            <div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('visual-assets.index') }}" class="rounded-xl border border-white/10 px-5 py-3 text-center font-bold hover:bg-white/5">Vazgeç</a><button class="rounded-xl bg-fuchsia-300 px-6 py-3 font-bold text-slate-950 hover:bg-fuchsia-200">Kaydet ve değerlendir</button></div>
        </form>
    </section>
</x-layouts.app>