<x-layouts.app title="{{ $asset->title }}">
    <section class="space-y-7">
        <header class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p class="text-sm font-bold tracking-[.18em] text-fuchsia-300">GÖRSEL DEĞERLENDİRMESİ</p><h1 class="mt-3 text-4xl font-black">{{ $asset->title }}</h1><p class="mt-2 text-slate-400">{{ $asset->agency->name }} · {{ $asset->source_type->label() }}</p></div><a href="{{ route('visual-assets.index') }}" class="rounded-xl border border-white/10 px-5 py-3 text-center font-bold hover:bg-white/5">Arşive dön</a></header>
        <div class="grid gap-7 xl:grid-cols-[1.45fr_.55fr]">
            <div class="space-y-5"><div class="relative aspect-video overflow-hidden rounded-2xl border border-white/10 bg-slate-900">@if($asset->storage_path)<img src="{{ route('visual-assets.file', $asset) }}" alt="{{ $asset->alt_text }}" class="h-full w-full object-contain">@elseif($asset->source_url)<img src="{{ $asset->source_url }}" alt="{{ $asset->alt_text }}" referrerpolicy="no-referrer" class="h-full w-full object-contain">@else<div class="grid h-full place-items-center bg-gradient-to-br from-fuchsia-950 to-slate-900"><div class="text-center"><div class="text-5xl">✦</div><strong class="mt-3 block text-fuchsia-200">Özgün üretim isteği kuyruğa hazır</strong></div></div>@endif @if($asset->headline_overlay)<strong class="absolute inset-x-0 bottom-0 bg-slate-950/85 p-5 text-2xl leading-tight sm:text-3xl">{{ $asset->headline_overlay }}</strong>@endif</div>
                <div class="rounded-2xl border border-white/10 bg-white/[.04] p-5"><h2 class="font-black">Değerlendirme notu</h2><p class="mt-3 text-slate-300">{{ $asset->evaluation_notes ?: 'Henüz değerlendirme yapılmadı.' }}</p>@if($asset->generation_prompt)<h3 class="mt-6 text-sm font-bold text-fuchsia-300">AI ÜRETİM PROMPTU</h3><p class="mt-2 whitespace-pre-line rounded-xl bg-slate-900 p-4 text-sm text-slate-300">{{ $asset->generation_prompt }}</p>@endif</div>
            </div>
            <aside class="space-y-5"><div class="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div class="flex items-center justify-between"><span class="text-sm text-slate-400">Kalite puanı</span><strong class="text-3xl {{ $asset->quality_score >= 70 ? 'text-emerald-300' : 'text-rose-300' }}">{{ $asset->quality_score }}</strong></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-slate-800"><div class="h-full rounded-full {{ $asset->quality_score >= 70 ? 'bg-emerald-300' : 'bg-rose-300' }}" style="width: {{ $asset->quality_score }}%"></div></div><dl class="mt-6 space-y-3 text-sm"><div class="flex justify-between gap-3"><dt class="text-slate-500">Durum</dt><dd class="font-bold">{{ $asset->status->label() }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Telif</dt><dd class="font-bold">{{ $asset->copyright_status->label() }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Boyut</dt><dd class="font-bold">{{ $asset->width && $asset->height ? $asset->width.' × '.$asset->height : 'Bilinmiyor' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Haber</dt><dd class="max-w-48 text-right font-bold">@if($asset->article)<a href="{{ route('articles.show', $asset->article) }}" class="hover:text-cyan-300">{{ $asset->article->title }}</a>@else Medya arşivi @endif</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Yükleyen</dt><dd class="font-bold">{{ $asset->uploader?->name ?? 'Otomasyon' }}</dd></div></dl></div>
                <div class="space-y-3 rounded-2xl border border-white/10 bg-white/[.04] p-5"><form method="POST" action="{{ route('visual-assets.evaluate', $asset) }}">@csrf<button class="w-full rounded-xl border border-fuchsia-300/30 px-4 py-3 font-bold text-fuchsia-200 hover:bg-fuchsia-300/10">Yeniden değerlendir</button></form>@if($asset->article_id && $asset->status === App\VisualAssetStatus::Approved && ! $asset->is_selected)<form method="POST" action="{{ route('visual-assets.select', $asset) }}">@csrf @method('PATCH')<button class="w-full rounded-xl bg-emerald-300 px-4 py-3 font-bold text-slate-950 hover:bg-emerald-200">Haber kapağı seç</button></form>@elseif($asset->is_selected)<div class="rounded-xl bg-emerald-400/10 px-4 py-3 text-center font-bold text-emerald-300">Aktif haber kapağı</div>@endif @can('delete', $asset)<form method="POST" action="{{ route('visual-assets.destroy', $asset) }}" onsubmit="return confirm('Bu görsel kaydı silinsin mi?')">@csrf @method('DELETE')<button class="w-full rounded-xl border border-rose-400/20 px-4 py-3 font-bold text-rose-300 hover:bg-rose-400/10">Kaydı sil</button></form>@endcan</div>
            </aside>
        </div>
    </section>
</x-layouts.app>