@php($currentPrompt = $prompt ?? null)
<div class="grid gap-6 lg:grid-cols-2">
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Şablon adı</span><input name="name" value="{{ old('name', $currentPrompt?->name) }}" required maxlength="150" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Kapsam</span><select name="agency_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300" @disabled(! auth()->user()->isSystemAdministrator())>@if(auth()->user()->isSystemAdministrator())<option value="">Global sistem şablonu</option>@endif @foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected((string) old('agency_id', $currentPrompt?->agency_id ?? auth()->user()->agency_id) === (string) $agency->id)>{{ $agency->name }}</option>@endforeach</select>@if(! auth()->user()->isSystemAdministrator())<input type="hidden" name="agency_id" value="{{ auth()->user()->agency_id }}">@endif</label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Kategori anahtarı</span><input name="category" list="prompt-categories" value="{{ old('category', $currentPrompt?->category ?? 'haber') }}" required pattern="[a-z0-9_-]+" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"><datalist id="prompt-categories">@foreach($categories as $category)<option value="{{ $category }}"></option>@endforeach</datalist></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Ton</span><select name="tone" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300">@foreach($tones as $tone)<option value="{{ $tone->value }}" @selected(old('tone', $currentPrompt?->tone?->value ?? App\PromptTone::Neutral->value) === $tone->value)>{{ $tone->label() }}</option>@endforeach</select></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Dil kodu</span><input name="language" value="{{ old('language', $currentPrompt?->language ?? 'tr') }}" required maxlength="10" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Hedef uzunluk (kelime)</span><input type="number" name="target_length" min="100" max="5000" value="{{ old('target_length', $currentPrompt?->target_length ?? 600) }}" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Yaratıcılık / temperature</span><input type="number" name="temperature" min="0" max="2" step="0.05" value="{{ old('temperature', $currentPrompt?->temperature ?? '0.70') }}" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"><small class="text-slate-500">0 daha tutarlı, 2 daha yaratıcı çıktı üretir.</small></label>
    <label class="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.03] px-4 py-3"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $currentPrompt?->is_active ?? true)) class="h-5 w-5 rounded border-white/20 bg-slate-900 text-cyan-300"><span><strong class="block">Aktif şablon</strong><small class="text-slate-500">İçerik üretim akışlarında seçilebilir.</small></span></label>
</div>
<label class="mt-6 block space-y-2"><span class="text-sm font-bold text-slate-300">Sistem promptu</span><textarea name="system_prompt" rows="6" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300">{{ old('system_prompt', $currentPrompt?->system_prompt) }}</textarea></label>
<label class="mt-6 block space-y-2"><span class="text-sm font-bold text-slate-300">Kullanıcı prompt şablonu</span><textarea name="user_prompt_template" rows="10" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 font-mono text-sm outline-none focus:border-cyan-300">{{ old('user_prompt_template', $currentPrompt?->user_prompt_template ?? "Aşağıdaki içeriği haber metnine dönüştür:\n\n{content}") }}</textarea><small class="text-slate-500"><code class="text-cyan-300">{content}</code> yer tutucusu zorunludur; kaynak içerik burada işlenir.</small></label>
<div class="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('prompts.index') }}" class="rounded-xl border border-white/10 px-5 py-3 text-center font-bold hover:bg-white/5">Vazgeç</a><button class="rounded-xl bg-cyan-300 px-6 py-3 font-bold text-slate-950 hover:bg-cyan-200">{{ $submitLabel }}</button></div>