<div class="grid gap-5 sm:grid-cols-2">
    <div class="sm:col-span-2"><label for="name" class="mb-2 block text-sm font-semibold">Ajans adı</label><input id="name" name="name" value="{{ old('name', $agency?->name) }}" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"><p class="mt-2 text-xs text-slate-500">Sistem adresi ajans adına göre otomatik oluşturulur.</p></div>
    <div><label for="contact_email" class="mb-2 block text-sm font-semibold">İletişim e-postası</label><input id="contact_email" name="contact_email" type="email" value="{{ old('contact_email', $agency?->contact_email) }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div><label for="phone" class="mb-2 block text-sm font-semibold">Telefon</label><input id="phone" name="phone" value="{{ old('phone', $agency?->phone) }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div><label for="subscription_starts_at" class="mb-2 block text-sm font-semibold">Üyelik başlangıcı</label><input id="subscription_starts_at" name="subscription_starts_at" type="date" value="{{ old('subscription_starts_at', $agency?->subscription_starts_at?->format('Y-m-d') ?? today()->format('Y-m-d')) }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div><label for="subscription_ends_at" class="mb-2 block text-sm font-semibold">Abonelik bitiş tarihi</label><input id="subscription_ends_at" name="subscription_ends_at" type="date" value="{{ old('subscription_ends_at', $agency?->subscription_ends_at?->format('Y-m-d')) }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div><label for="province" class="mb-2 block text-sm font-semibold">İl</label><input id="province" name="province" value="{{ old('province', $agency?->province) }}" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div><label for="district" class="mb-2 block text-sm font-semibold">İlçe</label><input id="district" name="district" value="{{ old('district', $agency?->district) }}" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div class="sm:col-span-2"><label for="category_name" class="mb-2 block text-sm font-semibold">Otomatik haber kategorisi</label><input id="category_name" name="category_name" value="{{ old('category_name', $agency?->category_name) }}" placeholder="İlçe Haberleri" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div class="sm:col-span-2"><label for="logo" class="mb-2 block text-sm font-semibold">Ajans logosu</label><input id="logo" name="logo" type="file" accept="image/jpeg,image/png,image/webp" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300">@if ($agency?->logo_path)<p class="mt-2 text-xs text-slate-500">Mevcut logo yüklü. Yeni dosya seçerseniz değiştirilir.</p>@endif</div>
    @if (! $agency)<div class="flex items-end"><input type="hidden" name="is_active" value="0"><label class="flex w-full items-center gap-3 rounded-xl border border-white/10 px-4 py-3"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', true))> Ajans aktif</label></div>@endif
</div>
<div class="mt-8 flex gap-3"><button class="rounded-xl bg-cyan-300 px-5 py-3 font-bold text-slate-950 hover:bg-cyan-200">{{ $submitLabel }}</button><a href="{{ route('agencies.index') }}" class="rounded-xl border border-white/10 px-5 py-3 hover:bg-white/5">Vazgeç</a></div>