<x-layouts.app title="Analitik ve Raporlama"><section class="space-y-7"><header class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p class="text-sm font-bold tracking-[.18em] text-teal-300">VERİYE DAYALI YÖNETİM</p><h1 class="mt-3 text-4xl font-black">Analitik ve Raporlama</h1><p class="mt-2 text-slate-400">İçerik üretimi, yayın başarısı, kampanya ve trend performansını gerçek sistem verileriyle izleyin.</p></div>@can('create',App\Models\AnalyticsSnapshot::class)<form method="POST" action="{{ route('analytics.refresh') }}" class="flex flex-col gap-2 sm:flex-row">@csrf
@if(auth()->user()->isSystemAdministrator())<select name="agency_id" class="rounded-xl border border-white/10 bg-slate-900 px-4 py-3"><option value="">Tüm aktif ajanslar</option>@foreach($agencies as $agency)<option value="{{ $agency->id }}">{{ $agency->name }}</option>@endforeach</select>@endif<button class="rounded-xl bg-teal-300 px-5 py-3 font-bold text-slate-950">Bugünü yenile</button></form>@endcan</header><form method="GET" action="{{ route('analytics.index') }}" class="grid gap-3 rounded-2xl border border-white/10 bg-white/[.04] p-4 sm:grid-cols-2 lg:grid-cols-4"><label class="space-y-1"><span class="text-xs text-slate-500">Başlangıç</span><input type="date" name="from" value="{{ request('from',now()->subDays(29)->toDateString()) }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label><label class="space-y-1"><span class="text-xs text-slate-500">Bitiş</span><input type="date" name="to" value="{{ request('to',now()->toDateString()) }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>@if(auth()->user()->isSystemAdministrator())<label class="space-y-1"><span class="text-xs text-slate-500">Ajans</span><select name="agency_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"><option value="">Tüm ajanslar</option>@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected((string)request('agency_id')===(string)$agency->id)>{{ $agency->name }}</option>@endforeach</select></label>@endif<div class="flex items-end gap-2"><button class="flex-1 rounded-xl border border-teal-300/30 px-5 py-3 font-bold text-teal-200">Uygula</button><a href="{{ route('analytics.export',request()->only(['from','to','agency_id'])) }}" class="rounded-xl border border-white/10 px-4 py-3 font-bold">CSV</a></div></form><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">@foreach([['Ham haber',$summary['raw_news']],['Üretilen',$summary['articles']],['Yayınlanan',$summary['published']],['Başarı %',number_format($summary['publication_success_rate'],1)],['Ort. SEO',number_format($summary['average_seo_score'],1)],['Kampanya',$summary['campaigns']],['Trend',$summary['trends']]] as [$label,$value])<div class="rounded-2xl border border-white/10 bg-white/[.04] p-4"><span class="text-xs text-slate-500">{{ $label }}</span><strong class="mt-2 block text-2xl">{{ $value }}</strong></div>@endforeach</div><article class="rounded-2xl border border-emerald-400/20 bg-emerald-400/[.03] p-5">
    <div class="flex flex-col justify-between gap-2 sm:flex-row sm:items-end">
        <div><p class="text-xs font-bold tracking-[.18em] text-emerald-300">KAYNAK PUAN TABLOSU</p><h2 class="mt-2 text-xl font-black">Hangi kaynak kaç haber verdi?</h2></div>
        <span class="text-sm text-slate-400">Seçili tarih aralığı</span>
    </div>
    <div class="mt-5 overflow-x-auto">
        <table class="w-full text-left text-sm">
            <thead class="border-b border-white/10 text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-3 py-3">#</th><th class="px-3 py-3">Kaynak</th><th class="px-3 py-3">Çekilen</th><th class="px-3 py-3">Hata</th><th class="px-3 py-3">Spam</th><th class="px-3 py-3">Görselsiz</th><th class="px-3 py-3">Yayın</th><th class="px-3 py-3">Günlük kota</th></tr></thead>
            <tbody class="divide-y divide-white/10">
                @forelse ($sourcePerformance as $source)
                    <tr><td class="px-3 py-3 font-black text-emerald-300">{{ $loop->iteration }}</td><td class="px-3 py-3"><strong>{{ $source->name }}</strong><span class="block text-xs text-slate-500">{{ $source->domain }}</span></td><td class="px-3 py-3 font-bold">{{ $source->collected_count }}</td><td class="px-3 py-3 text-rose-300">{{ $source->failed_count }}</td><td class="px-3 py-3 text-amber-300">{{ $source->rejected_count }}</td><td class="px-3 py-3">{{ $source->missing_image_count }}</td><td class="px-3 py-3 font-black text-emerald-300">{{ $source->published_count }}</td><td class="px-3 py-3">{{ $source->daily_item_limit }}</td></tr>
                @empty
                    <tr><td colspan="8" class="px-3 py-10 text-center text-slate-400">Tanımlı haber kaynağı bulunmuyor.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
</article><article class="rounded-2xl border border-white/10 bg-white/[.04] p-5"><h2 class="text-xl font-black">Günlük yayın hacmi</h2><div class="mt-6 flex h-56 items-end gap-1 overflow-x-auto border-b border-white/10 pb-1" role="img" aria-label="Günlük yayınlanan haber grafiği">@forelse($series as $day)<div class="min-w-4 flex-1 rounded-t bg-gradient-to-t from-teal-700 to-teal-300" style="height: {{ max(4,($day['published']/$maxPublished)*100) }}%" title="{{ $day['date'] }} · {{ $day['published'] }} yayın"></div>@empty<p class="m-auto text-slate-500">Seçili aralıkta snapshot yok. Bugünü yenileyin.</p>@endforelse</div></article><div class="overflow-hidden rounded-2xl border border-white/10 bg-white/[.04]"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-white/10 text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-4 py-3">Tarih / Ajans</th><th class="px-4 py-3">Ham</th><th class="px-4 py-3">Üretim</th><th class="px-4 py-3">Yayın</th><th class="px-4 py-3">Başarı</th><th class="px-4 py-3">SEO</th><th class="px-4 py-3">Kampanya</th><th class="px-4 py-3">Trend</th></tr></thead><tbody class="divide-y divide-white/10">@forelse($snapshots as $snapshot)<tr><td class="px-4 py-3"><strong>{{ $snapshot->report_date->format('d.m.Y') }}</strong><span class="block text-xs text-slate-500">{{ $snapshot->agency->name }}</span></td><td class="px-4 py-3">{{ $snapshot->raw_news_count }}</td><td class="px-4 py-3">{{ $snapshot->articles_created_count }}</td><td class="px-4 py-3">{{ $snapshot->articles_published_count }}</td><td class="px-4 py-3">%{{ number_format($snapshot->publicationSuccessRate(),1) }}</td><td class="px-4 py-3">{{ $snapshot->average_seo_score===null?'—':number_format($snapshot->average_seo_score,1) }}</td><td class="px-4 py-3">{{ $snapshot->campaigns_created_count }}</td><td class="px-4 py-3">{{ $snapshot->trend_topics_count }}</td></tr>@empty<tr><td colspan="8" class="px-5 py-14 text-center text-slate-400">Rapor verisi bulunmuyor.</td></tr>@endforelse</tbody></table></div>@if($snapshots->hasPages())<div class="border-t border-white/10 px-5 py-4">{{ $snapshots->links() }}</div>@endif</div></section></x-layouts.app>