<x-layouts.app title="Ham haber ekle">
    <section class="mx-auto max-w-4xl"><p class="text-sm font-bold tracking-[.18em] text-cyan-300">HAM HABER HAVUZU</p><h1 class="mt-3 text-4xl font-black">Manuel ham veri ekle</h1><p class="mt-2 text-slate-400">Ajans veya web kaynağından alınan işlenmemiş içeriği havuza aktarın.</p>
        <div class="mt-8 rounded-2xl border border-white/10 bg-white/[.04] p-6 sm:p-8"><form method="POST" action="{{ route('raw-news.store') }}" class="grid gap-5 sm:grid-cols-2">@csrf
            @if (auth()->user()->isSystemAdministrator())<div class="sm:col-span-2"><label for="agency_id" class="mb-2 block text-sm font-semibold">Ajans</label><select id="agency_id" name="agency_id" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"><option value="">Ajans seçin</option>@foreach ($agencies as $agency)<option value="{{ $agency->id }}" @selected((string) old('agency_id') === (string) $agency->id)>{{ $agency->name }}</option>@endforeach</select></div>@else<input type="hidden" name="agency_id" value="{{ auth()->user()->agency_id }}">@endif
            <div><label for="source_name" class="mb-2 block text-sm font-semibold">Kaynak adı</label><input id="source_name" name="source_name" value="{{ old('source_name') }}" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
            <div><label for="external_id" class="mb-2 block text-sm font-semibold">Kaynak kayıt kimliği</label><input id="external_id" name="external_id" value="{{ old('external_id') }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
            <div class="sm:col-span-2"><label for="source_url" class="mb-2 block text-sm font-semibold">Kaynak bağlantısı</label><input id="source_url" name="source_url" type="url" value="{{ old('source_url') }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
            <div class="sm:col-span-2"><label for="original_title" class="mb-2 block text-sm font-semibold">Orijinal başlık</label><input id="original_title" name="original_title" value="{{ old('original_title') }}" required maxlength="500" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-lg font-semibold outline-none focus:border-cyan-300"></div>
            <div class="sm:col-span-2"><label for="original_body" class="mb-2 block text-sm font-semibold">Orijinal metin</label><textarea id="original_body" name="original_body" rows="12" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 leading-7 outline-none focus:border-cyan-300">{{ old('original_body') }}</textarea></div>
            <div class="sm:col-span-2"><label for="original_image_url" class="mb-2 block text-sm font-semibold">Orijinal görsel bağlantısı</label><input id="original_image_url" name="original_image_url" type="url" value="{{ old('original_image_url') }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
            <div><label for="language" class="mb-2 block text-sm font-semibold">Dil kodu</label><input id="language" name="language" value="{{ old('language', 'tr') }}" maxlength="10" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
            <div><label for="priority" class="mb-2 block text-sm font-semibold">Öncelik (0-100)</label><input id="priority" name="priority" type="number" min="0" max="100" value="{{ old('priority', 50) }}" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
            <div class="flex flex-wrap gap-3 sm:col-span-2"><button class="rounded-xl bg-cyan-300 px-5 py-3 font-bold text-slate-950 hover:bg-cyan-200">Havuza ekle</button><a href="{{ route('raw-news.index') }}" class="rounded-xl border border-white/10 px-5 py-3 hover:bg-white/5">Vazgeç</a></div>
        </form></div>
    </section>
</x-layouts.app>