<x-layouts.app title="Ham Haberi Düzenle"><section class="mx-auto max-w-4xl"><p class="text-sm font-bold tracking-[.18em] text-cyan-300">HAM HABER HAVUZU</p><h1 class="mt-3 text-4xl font-black">Ham haberi düzenle</h1>
<div class="mt-8 rounded-2xl border border-white/10 bg-white/[.04] p-6"><form method="POST" action="{{ route('raw-news.update',$item) }}" class="grid gap-5 sm:grid-cols-2">@csrf @method('PUT')
<label>Kaynak adı<input name="source_name" value="{{ old('source_name',$item->source_name) }}" required class="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label>Kayıt kimliği<input name="external_id" value="{{ old('external_id',$item->external_id) }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label class="sm:col-span-2">Kaynak bağlantısı<input type="url" name="source_url" value="{{ old('source_url',$item->source_url) }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label class="sm:col-span-2">Başlık<input name="original_title" value="{{ old('original_title',$item->original_title) }}" required class="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label class="sm:col-span-2">Metin<textarea name="original_body" rows="14" required class="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3">{{ old('original_body',$item->original_body) }}</textarea></label>
<label class="sm:col-span-2">Görsel bağlantısı<input type="url" name="original_image_url" value="{{ old('original_image_url',$item->original_image_url) }}" class="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label>Dil<input name="language" value="{{ old('language',$item->language) }}" required class="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label>Öncelik<input type="number" min="0" max="100" name="priority" value="{{ old('priority',$item->priority) }}" required class="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<div class="flex gap-3 sm:col-span-2"><button class="rounded-xl bg-cyan-300 px-5 py-3 font-black text-slate-950">Güncelle ve yeniden işle</button><a href="{{ route('raw-news.show',$item) }}" class="rounded-xl border border-white/10 px-5 py-3">Vazgeç</a></div></form></div></section></x-layouts.app>
