<x-layouts.app :title="$item->original_title">
    <article class="mx-auto max-w-4xl">
        <div class="flex flex-wrap items-center gap-2 text-xs font-bold"><span class="rounded-full px-3 py-1 {{ match($item->status) { App\RawNewsStatus::Processed => 'bg-emerald-400/10 text-emerald-300', App\RawNewsStatus::Queued, App\RawNewsStatus::Processing => 'bg-cyan-400/10 text-cyan-300', App\RawNewsStatus::Failed => 'bg-rose-400/10 text-rose-300', App\RawNewsStatus::Rejected => 'bg-slate-400/10 text-slate-400', default => 'bg-amber-400/10 text-amber-300' } }}">{{ $item->status->label() }}</span><span class="rounded-full bg-white/5 px-3 py-1 text-slate-400">Öncelik {{ $item->priority }}</span><span class="rounded-full bg-indigo-400/10 px-3 py-1 text-indigo-200">{{ strtoupper($item->language) }}</span></div>
        <h1 class="mt-6 text-4xl font-black leading-tight tracking-tight sm:text-6xl">{{ $item->original_title }}</h1>
        <dl class="mt-6 grid gap-4 border-y border-white/10 py-5 text-sm sm:grid-cols-3"><div><dt class="text-slate-500">Ajans</dt><dd class="mt-1 font-bold">{{ $item->agency->name }}</dd></div><div><dt class="text-slate-500">Kaynak</dt><dd class="mt-1 font-bold">{{ $item->source_name }}</dd></div><div><dt class="text-slate-500">Keşif zamanı</dt><dd class="mt-1 font-bold">{{ $item->discovered_at?->format('d.m.Y H:i') ?? 'Bilinmiyor' }}</dd></div></dl>
        <div class="mt-8 whitespace-pre-line text-lg leading-8 text-slate-200">{{ $item->original_body }}</div>
        @if ($item->failure_message)<div class="mt-8 rounded-xl border border-rose-400/20 bg-rose-400/10 p-5"><strong class="text-rose-200">İşleme hatası</strong><p class="mt-2 text-slate-300">{{ $item->failure_message }}</p></div>@endif
        <div class="mt-8 grid gap-4 rounded-xl border border-white/10 bg-white/[.04] p-5 sm:grid-cols-2"><div><span class="text-xs font-bold tracking-wider text-slate-500">KAYNAK BAĞLANTISI</span>@if ($item->source_url)<a href="{{ $item->source_url }}" target="_blank" rel="noopener noreferrer" class="mt-2 block break-all text-sm text-cyan-300">{{ $item->source_url }}</a>@else<p class="mt-2 text-sm text-slate-400">Bağlantı yok</p>@endif</div><div><span class="text-xs font-bold tracking-wider text-slate-500">ORİJİNAL GÖRSEL</span>@if ($item->original_image_url)<a href="{{ $item->original_image_url }}" target="_blank" rel="noopener noreferrer" class="mt-2 block break-all text-sm text-cyan-300">Görseli yeni sekmede aç</a>@else<p class="mt-2 text-sm text-slate-400">Görsel yok</p>@endif</div></div>
        <div class="mt-10 flex flex-wrap gap-3"><a href="{{ route('raw-news.index') }}" class="rounded-xl border border-white/10 px-5 py-3 hover:bg-white/5">← Ham Haber Havuzu</a>@can('update',$item)<a href="{{ route('raw-news.edit',$item) }}" class="rounded-xl border border-cyan-400/20 px-5 py-3 font-bold text-cyan-300">Düzenle</a>@endcan
@if (in_array($item->status, [App\RawNewsStatus::Pending, App\RawNewsStatus::Failed], true))<form method="POST" action="{{ route('raw-news.bulk-action') }}">@csrf @method('PATCH')<input type="hidden" name="items[]" value="{{ $item->id }}"><button name="action" value="queue" class="rounded-xl bg-cyan-300 px-5 py-3 font-bold text-slate-950 hover:bg-cyan-200">Kuyruğa al</button></form>@endif @can('delete', $item)<form method="POST" action="{{ route('raw-news.destroy', $item) }}">@csrf @method('DELETE')<button class="rounded-xl border border-rose-400/20 px-5 py-3 font-bold text-rose-300 hover:bg-rose-400/10">Ham veriyi sil</button></form>@endcan</div>
    </article>
</x-layouts.app>