<x-layouts.app title="Yayın Merkezi">
    <section class="space-y-7">
        <header class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p class="text-sm font-bold tracking-[.18em] text-amber-300">ÇOKLU KANAL DAĞITIMI</p><h1 class="mt-3 text-4xl font-black">Yayın Merkezi</h1><p class="mt-2 text-slate-400">WordPress yayın kuyruklarını, uzak kimlikleri ve sonuçları tek ekrandan izleyin.</p></div><div class="flex flex-col gap-2 sm:flex-row">@can('viewAny', App\Models\PublishingTarget::class)<a href="{{ route('publishing-targets.index') }}" class="rounded-xl border border-white/10 px-5 py-3 text-center font-bold">Hedefler</a>@endcan @can('create', App\Models\Publication::class)<a href="{{ route('publications.multi-site') }}" class="rounded-xl border border-violet-400/30 px-5 py-3 text-center font-bold text-violet-200">Çoklu dağıtım</a><a href="{{ route('publications.create') }}" class="rounded-xl bg-amber-300 px-5 py-3 text-center font-bold text-slate-950">+ Yayın oluştur</a>@endcan</div></header>
        @can('create', App\Models\Publication::class)
            @if ($failedPublicationCount > 0)
                <form method="POST" action="{{ route('publications.dispatch-failed') }}" onsubmit="return confirm('{{ $failedPublicationCount }} hatalı yayın yeniden kuyruğa alınsın mı?')" class="flex justify-end">
                    @csrf
                    <button class="rounded-xl bg-rose-300 px-5 py-3 font-black text-rose-950">Tüm hatalıları kuyruğa al ({{ $failedPublicationCount }})</button>
                </form>
            @endif
        @endcan
        <form method="GET" class="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[.04] p-4 sm:flex-row"><select name="status" class="flex-1 rounded-xl border border-white/10 bg-slate-900 px-4 py-3"><option value="">Tüm durumlar</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select><button class="rounded-xl border border-amber-300/30 px-5 py-3 font-bold text-amber-200">Filtrele</button></form>
        <div class="overflow-hidden rounded-2xl border border-white/10 bg-white/[.04]"><div class="overflow-x-auto"><table class="w-full text-left"><thead class="border-b border-white/10 text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-4">Haber</th><th class="px-5 py-4">Hedef</th><th class="px-5 py-4">Durum</th><th class="px-5 py-4">Uzak kayıt</th><th class="px-5 py-4 text-right">İşlem</th></tr></thead><tbody class="divide-y divide-white/10">@forelse($publications as $publication)<tr><td class="max-w-md px-5 py-4"><strong>{{ $publication->article->title }}</strong><span class="mt-1 block text-xs text-slate-500">{{ $publication->agency->name }} · {{ $publication->created_at->format('d.m.Y H:i') }}</span></td><td class="px-5 py-4 text-sm">{{ $publication->publishingTarget->name }}</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ match($publication->status) { App\PublicationStatus::Published => 'bg-emerald-400/10 text-emerald-300', App\PublicationStatus::Failed => 'bg-rose-400/10 text-rose-300', App\PublicationStatus::Publishing => 'bg-cyan-400/10 text-cyan-300', default => 'bg-amber-400/10 text-amber-300' } }}">{{ $publication->status->label() }}</span></td><td class="px-5 py-4 text-sm"><span>{{ $publication->remote_post_id ? '#'.$publication->remote_post_id : '—' }}</span><span class="mt-1 block text-xs text-slate-500">{{ $publication->remote_status->label() }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('publications.show', $publication) }}" class="rounded-lg border border-white/10 px-3 py-2 text-sm">İncele</a></td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-slate-400">Henüz yayın kaydı bulunmuyor.</td></tr>@endforelse</tbody></table></div>@if($publications->hasPages())<div class="border-t border-white/10 px-5 py-4">{{ $publications->links() }}</div>@endif</div>
    </section>
</x-layouts.app>