<x-layouts.app title="Çoklu Site Dağıtımı">
<section class="mx-auto max-w-5xl space-y-7">
<header><a href="{{ route('publications.index') }}" class="text-amber-300">← Yayın Merkezi</a><p class="mt-5 text-sm font-bold tracking-[.18em] text-violet-300">ÇOKLU HEDEF</p><h1 class="mt-3 text-4xl font-black">Çoklu Site Dağıtımı</h1><p class="mt-2 text-slate-400">Tek bir onaylı haberi aynı işlem içinde 2–20 WordPress hedefine dağıtın.</p></header>
<form method="POST" action="{{ route('publications.multi-site.store') }}" class="space-y-6">@csrf
<div class="grid gap-5 rounded-2xl border border-white/10 bg-white/[.04] p-6 lg:grid-cols-2">
<label><span class="mb-1 block text-sm font-bold">Ajans</span><select name="agency_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3" @disabled(! auth()->user()->isSystemAdministrator())>@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected((string)old('agency_id',auth()->user()->agency_id)===(string)$agency->id)>{{ $agency->name }}</option>@endforeach</select>@if(!auth()->user()->isSystemAdministrator())<input type="hidden" name="agency_id" value="{{ auth()->user()->agency_id }}">@endif</label>
<label><span class="mb-1 block text-sm font-bold">Haber</span><select name="article_id" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"><option value="">Onaylı haber seçin</option>@foreach($articles as $article)<option value="{{ $article->id }}" @selected((string)old('article_id')===(string)$article->id)>{{ $article->title }} · {{ $article->agency->name }}</option>@endforeach</select></label>
<fieldset class="lg:col-span-2"><legend class="mb-2 text-sm font-bold">Yayın hedefleri (en az 2)</legend><div class="grid gap-3 sm:grid-cols-2">@foreach($targets as $target)<label class="flex items-center gap-3 rounded-xl border border-white/10 bg-slate-900/60 p-4"><input type="checkbox" name="publishing_target_ids[]" value="{{ $target->id }}" @checked(in_array((string) $target->id, array_map('strval', old('publishing_target_ids', [])), true))><span><strong class="block">{{ $target->name }}</strong><small class="text-slate-500">{{ $target->agency->name }} · {{ $target->base_url }}</small></span></label>@endforeach</div></fieldset>
<label><span class="mb-1 block text-sm font-bold">Uzak yayın durumu</span><select name="remote_status" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3">@foreach($remoteStatuses as $status)<option value="{{ $status->value }}" @selected(old('remote_status',App\RemotePublicationStatus::Draft->value)===$status->value)>{{ $status->label() }}</option>@endforeach</select></label>
<label><span class="mb-1 block text-sm font-bold">Uzak yazar ID</span><input type="number" min="1" name="remote_author_id" value="{{ old('remote_author_id') }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label><span class="mb-1 block text-sm font-bold">Kategori ID'leri</span><input name="remote_category_ids" value="{{ old('remote_category_ids') }}" placeholder="2,5" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label><span class="mb-1 block text-sm font-bold">Etiket ID'leri</span><input name="remote_tag_ids" value="{{ old('remote_tag_ids') }}" placeholder="8,11" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label><span class="mb-1 block text-sm font-bold">İleri yayın zamanı</span><input type="datetime-local" name="scheduled_for" value="{{ old('scheduled_for') }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"></label>
<label><span class="mb-1 block text-sm font-bold">Saat dilimi</span><select name="schedule_timezone" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3"><option value="Europe/Istanbul">Europe/Istanbul</option><option value="UTC">UTC</option></select></label>
</div><div class="flex justify-end"><button class="rounded-xl bg-violet-300 px-6 py-3 font-black text-slate-950">Tüm hedeflere dağıt</button></div></form>
</section></x-layouts.app>
