<x-layouts.app title="Üretim Bandı Oluştur">
    <section class="mx-auto max-w-6xl space-y-7">
        <header><p class="text-sm font-bold tracking-[.18em] text-violet-300">İÇERİK FABRİKASI</p><h1 class="mt-3 text-4xl font-black">Yeni üretim bandı</h1><p class="mt-2 text-slate-400">Uygun ham haberleri seçin; prompt sürümü bu batch için dondurularak içerikler kuyrukta işlenir.</p></header>
        <form method="POST" action="{{ route('content-batches.store') }}" class="space-y-6">@csrf
            <div class="grid gap-5 rounded-2xl border border-white/10 bg-white/[.04] p-5 lg:grid-cols-3"><label class="space-y-2"><span class="text-sm font-bold text-slate-300">Band adı</span><input name="name" value="{{ old('name', 'Günlük Üretim '.now()->format('d.m.Y H:i')) }}" required maxlength="180" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-violet-300"></label><label class="space-y-2"><span class="text-sm font-bold text-slate-300">Ajans</span><select name="agency_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-violet-300" @disabled(! auth()->user()->isSystemAdministrator())>@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected((string) old('agency_id', auth()->user()->agency_id) === (string) $agency->id)>{{ $agency->name }}</option>@endforeach</select>@if(! auth()->user()->isSystemAdministrator())<input type="hidden" name="agency_id" value="{{ auth()->user()->agency_id }}">@endif</label><label class="space-y-2"><span class="text-sm font-bold text-slate-300">Prompt şablonu</span><select name="ai_prompt_id" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-violet-300"><option value="">Prompt seçin</option>@foreach($prompts as $prompt)<option value="{{ $prompt->id }}" @selected((string) old('ai_prompt_id') === (string) $prompt->id)>{{ $prompt->name }} · {{ $prompt->agency?->name ?? 'Global' }} · v{{ $prompt->version }}</option>@endforeach</select></label></div>
            <div class="overflow-hidden rounded-2xl border border-white/10 bg-white/[.04]"><div class="border-b border-white/10 p-5"><h2 class="text-xl font-black">Üretilecek ham haberler</h2><p class="mt-1 text-sm text-slate-400">Bekleyen veya önceki denemesi hatalı olan en fazla 500 kayıt seçilebilir.</p></div><div class="max-h-[60vh] overflow-auto"><table class="w-full text-left"><thead class="sticky top-0 bg-slate-900 text-xs uppercase tracking-wider text-slate-400"><tr><th class="w-12 px-5 py-4">Seç</th><th class="px-5 py-4">Ham haber</th><th class="px-5 py-4">Ajans / Kaynak</th><th class="px-5 py-4">Durum</th></tr></thead><tbody class="divide-y divide-white/10">@forelse($rawNewsItems as $item)<tr class="align-top"><td class="px-5 py-4"><input type="checkbox" name="raw_news_ids[]" value="{{ $item->id }}" @checked(in_array($item->id, old('raw_news_ids', []))) class="h-5 w-5 rounded border-white/20 bg-slate-900 text-violet-300" aria-label="{{ $item->original_title }} seç"></td><td class="max-w-2xl px-5 py-4"><strong>{{ $item->original_title }}</strong><p class="mt-1 line-clamp-2 text-sm text-slate-400">{{ Str::limit($item->original_body, 150) }}</p></td><td class="px-5 py-4 text-sm"><strong>{{ $item->agency->name }}</strong><span class="mt-1 block text-slate-500">{{ $item->source_name }}</span></td><td class="px-5 py-4 text-sm">{{ $item->status->label() }}<span class="mt-1 block text-xs text-slate-500">Öncelik {{ $item->priority }}</span></td></tr>@empty<tr><td colspan="4" class="px-5 py-14 text-center text-slate-400">Üretime uygun ham haber bulunmuyor.</td></tr>@endforelse</tbody></table></div></div>
            <div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('content-batches.index') }}" class="rounded-xl border border-white/10 px-5 py-3 text-center font-bold hover:bg-white/5">Vazgeç</a><button class="rounded-xl bg-violet-300 px-6 py-3 font-bold text-slate-950 hover:bg-violet-200">Bandı oluştur ve kuyruğa gönder</button></div>
        </form>
    </section>
</x-layouts.app>