@php($currentTarget = $target ?? null)
<div class="grid gap-6 lg:grid-cols-2">
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Hedef adı</span><input name="name" value="{{ old('name', $currentTarget?->name) }}" required maxlength="150" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-emerald-300"></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Ajans</span><select name="agency_id" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-emerald-300" @disabled(! auth()->user()->isSystemAdministrator())>@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected((string) old('agency_id', $currentTarget?->agency_id ?? auth()->user()->agency_id) === (string) $agency->id)>{{ $agency->name }}</option>@endforeach</select>@if(! auth()->user()->isSystemAdministrator())<input type="hidden" name="agency_id" value="{{ auth()->user()->agency_id }}">@endif</label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">WordPress adresi</span><input type="url" name="base_url" value="{{ old('base_url', $currentTarget?->base_url) }}" placeholder="https://haber.example.com" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-emerald-300"><small class="text-slate-500">Alan adını yazın; REST ve XML-RPC yolu otomatik eklenir.</small></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Protokol</span><select name="protocol" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-emerald-300">@foreach($protocols as $protocol)<option value="{{ $protocol->value }}" @selected(old('protocol', $currentTarget?->protocol?->value ?? App\PublishingProtocol::WordPressRest->value) === $protocol->value)>{{ $protocol->label() }}</option>@endforeach</select></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">WordPress kullanıcı adı</span><input name="username" value="{{ old('username', $currentTarget?->username) }}" required autocomplete="off" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-emerald-300"></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Uygulama parolası</span><input type="password" name="credential" @required(! $currentTarget) autocomplete="new-password" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-emerald-300"><small class="text-slate-500">{{ $currentTarget ? 'Değiştirmeyecekseniz boş bırakın.' : 'WordPress kullanıcı profilinden oluşturulan uygulama parolası.' }}</small></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Varsayılan yazar ID</span><input type="number" min="1" name="default_author_id" value="{{ old('default_author_id', $currentTarget?->default_author_id) }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-emerald-300"></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Varsayılan kategori ID’leri</span><input name="default_category_ids" value="{{ old('default_category_ids', implode(',', $currentTarget?->default_category_ids ?? [])) }}" placeholder="2,5,8" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-emerald-300"></label>
    <label class="space-y-2"><span class="text-sm font-bold text-slate-300">Varsayılan etiket ID’leri</span><input name="default_tag_ids" value="{{ old('default_tag_ids', implode(',', $currentTarget?->default_tag_ids ?? [])) }}" placeholder="11,14" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-emerald-300"></label>
    <label class="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.03] px-4 py-3"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $currentTarget?->is_active ?? true)) class="h-5 w-5 rounded border-white/20 bg-slate-900 text-emerald-300"><span><strong class="block">Aktif hedef</strong><small class="text-slate-500">Yeni yayınlarda seçilebilir.</small></span></label>
</div>
<div class="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('publishing-targets.index') }}" class="rounded-xl border border-white/10 px-5 py-3 text-center font-bold hover:bg-white/5">Vazgeç</a><button class="rounded-xl bg-emerald-300 px-6 py-3 font-bold text-slate-950 hover:bg-emerald-200">{{ $submitLabel }}</button></div>