<div class="grid gap-5 sm:grid-cols-2">
    @if (auth()->user()->isSystemAdministrator())
        <div class="sm:col-span-2"><label for="agency_id" class="mb-2 block text-sm font-semibold">Ajans</label><select id="agency_id" name="agency_id" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"><option value="">Ajans seçin</option>@foreach ($agencies as $agency)<option value="{{ $agency->id }}" @selected((string) old('agency_id', $article?->agency_id) === (string) $agency->id)>{{ $agency->name }}</option>@endforeach</select></div>
    @else
        <input type="hidden" name="agency_id" value="{{ auth()->user()->agency_id }}">
    @endif
    <div class="sm:col-span-2"><label for="title" class="mb-2 block text-sm font-semibold">Haber başlığı</label><input id="title" name="title" value="{{ old('title', $article?->title) }}" maxlength="255" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-lg font-semibold outline-none focus:border-cyan-300"></div>
    <div class="sm:col-span-2"><label for="summary" class="mb-2 block text-sm font-semibold">Kısa özet</label><textarea id="summary" name="summary" rows="3" maxlength="1000" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300">{{ old('summary', $article?->summary) }}</textarea></div>
    <div class="sm:col-span-2"><label for="body" class="mb-2 block text-sm font-semibold">Haber metni</label><textarea id="body" name="body" rows="14" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 leading-7 outline-none focus:border-cyan-300">{{ old('body', $article?->body) }}</textarea><p class="mt-2 text-xs text-slate-500">Metin güvenli düz içerik olarak saklanır; HTML kodları çalıştırılmaz.</p></div>
    <div><label for="status" class="mb-2 block text-sm font-semibold">Yayın durumu</label><select id="status" name="status" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300">@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', $article?->status?->value ?? App\ArticleStatus::Draft->value) === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
    <div><label for="source_trust_status" class="mb-2 block text-sm font-semibold">Kaynak güveni</label><select id="source_trust_status" name="source_trust_status" required class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300">@foreach ($trustStatuses as $trustStatus)<option value="{{ $trustStatus->value }}" @selected(old('source_trust_status', $article?->source_trust_status?->value ?? App\SourceTrustStatus::Unverified->value) === $trustStatus->value)>{{ $trustStatus->label() }}</option>@endforeach</select></div>
    <div><label for="source_name" class="mb-2 block text-sm font-semibold">Kaynak adı</label><input id="source_name" name="source_name" value="{{ old('source_name', $article?->source_name) }}" maxlength="255" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div><label for="source_url" class="mb-2 block text-sm font-semibold">Kaynak bağlantısı</label><input id="source_url" name="source_url" type="url" value="{{ old('source_url', $article?->source_url) }}" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"></div>
    <div class="sm:col-span-2"><label for="failure_message" class="mb-2 block text-sm font-semibold">Hata açıklaması <span class="font-normal text-slate-500">(yalnızca hatalı içerik)</span></label><textarea id="failure_message" name="failure_message" rows="2" maxlength="2000" class="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300">{{ old('failure_message', $article?->failure_message) }}</textarea></div>
</div>
<div class="mt-8 flex flex-wrap gap-3"><button class="rounded-xl bg-cyan-300 px-5 py-3 font-bold text-slate-950 hover:bg-cyan-200">{{ $submitLabel }}</button><a href="{{ $article ? route('articles.show', $article) : route('articles.index') }}" class="rounded-xl border border-white/10 px-5 py-3 hover:bg-white/5">Vazgeç</a></div>