<x-layouts.app :title="$article->title">
    <article class="mx-auto max-w-4xl">
        <div class="flex flex-wrap items-center gap-2 text-xs font-bold"><span class="rounded-full px-3 py-1 {{ match($article->status) { App\ArticleStatus::Published => 'bg-emerald-400/10 text-emerald-300', App\ArticleStatus::PendingApproval => 'bg-amber-400/10 text-amber-300', App\ArticleStatus::Failed => 'bg-rose-400/10 text-rose-300', default => 'bg-slate-400/10 text-slate-300' } }}">{{ $article->status->label() }}</span><span class="rounded-full bg-indigo-400/10 px-3 py-1 text-indigo-200">{{ $article->source_trust_status->label() }}</span><span class="rounded-full bg-white/5 px-3 py-1 text-slate-400">{{ $article->agency->name }}</span></div>
        <h1 class="mt-6 text-4xl font-black leading-tight tracking-tight sm:text-6xl">{{ $article->title }}</h1>
        @if ($article->selectedVisualAsset)<div class="relative mt-8 aspect-video overflow-hidden rounded-2xl border border-white/10 bg-slate-900">@if($article->selectedVisualAsset->storage_path)<img src="{{ route('visual-assets.file', $article->selectedVisualAsset) }}" alt="{{ $article->selectedVisualAsset->alt_text }}" class="h-full w-full object-cover">@elseif($article->selectedVisualAsset->source_url)<img src="{{ $article->selectedVisualAsset->source_url }}" alt="{{ $article->selectedVisualAsset->alt_text }}" referrerpolicy="no-referrer" class="h-full w-full object-cover">@endif @if($article->selectedVisualAsset->headline_overlay)<strong class="absolute inset-x-0 bottom-0 bg-slate-950/85 p-5 text-2xl leading-tight sm:text-3xl">{{ $article->selectedVisualAsset->headline_overlay }}</strong>@endif</div>@endif        @if ($article->summary)<p class="mt-6 border-l-2 border-cyan-300 pl-5 text-xl leading-8 text-slate-300">{{ $article->summary }}</p>@endif
        <div class="mt-6 flex flex-wrap gap-x-5 gap-y-2 border-y border-white/10 py-4 text-sm text-slate-400"><span>Yazar: <strong class="text-slate-200">{{ $article->author?->name ?? 'ASYA Otomasyon' }}</strong></span><span>Güncelleme: <strong class="text-slate-200">{{ $article->updated_at->format('d.m.Y H:i') }}</strong></span>@if ($article->published_at)<span>Yayın: <strong class="text-slate-200">{{ $article->published_at->format('d.m.Y H:i') }}</strong></span>@endif</div>
        <div class="mt-8 whitespace-pre-line text-lg leading-8 text-slate-200">{{ $article->body }}</div>
        @if ($article->failure_message)<div class="mt-8 rounded-xl border border-rose-400/20 bg-rose-400/10 p-5"><strong class="text-rose-200">Hata açıklaması</strong><p class="mt-2 text-slate-300">{{ $article->failure_message }}</p></div>@endif
        @if ($article->source_name || $article->source_url)<div class="mt-8 rounded-xl border border-white/10 bg-white/[.04] p-5"><span class="text-xs font-bold tracking-wider text-slate-500">KAYNAK</span><strong class="mt-2 block">{{ $article->source_name ?: 'Kaynak bağlantısı' }}</strong>@if ($article->source_url)<a href="{{ $article->source_url }}" target="_blank" rel="noopener noreferrer" class="mt-2 block break-all text-sm text-cyan-300 hover:text-cyan-200">{{ $article->source_url }}</a>@endif</div>@endif
        <div class="mt-10 flex flex-wrap gap-3"><a href="{{ route('articles.index') }}" class="rounded-xl border border-white/10 px-5 py-3 hover:bg-white/5">← Haber Merkezi</a>@can('update', $article)@if($article->status === App\ArticleStatus::Failed)<form method="POST" action="{{ route('articles.retry',$article) }}">@csrf<button class="rounded-xl border border-amber-400/20 px-5 py-3 font-bold text-amber-300">Yeniden dene</button></form>@endif<a href="{{ route('visual-assets.create', ['article_id' => $article->id]) }}" class="rounded-xl border border-fuchsia-400/20 px-5 py-3 font-bold text-fuchsia-300 hover:bg-fuchsia-400/10">Görsel Ekle</a><a href="{{ route('seo.show', $article) }}" class="rounded-xl border border-indigo-400/20 px-5 py-3 font-bold text-indigo-300 hover:bg-indigo-400/10">SEO Analizi</a><a href="{{ route('articles.edit', $article) }}" class="rounded-xl bg-cyan-300 px-5 py-3 font-bold text-slate-950 hover:bg-cyan-200">Düzenle</a>@endcan @can('delete', $article)<form method="POST" action="{{ route('articles.destroy', $article) }}">@csrf @method('DELETE')<button class="rounded-xl border border-rose-400/20 px-5 py-3 font-bold text-rose-300 hover:bg-rose-400/10">Haberi sil</button></form>@endcan</div>
    </article>
</x-layouts.app>